### ISSUE TITLE
ics文件 UID属性

### ISSUE THREAD

**Issue by cnafan** [cunzao/xidian-class-shedule#2]
UID属性不应该是唯一的嘛，你是以课程代码作为标识，那同一门课程的不同时间的课不是就重叠了么，
这样最后就日程里只有每门课的某一节课了

**Comment by cnafan** [comment]
为啥你能导入成功 :neutral_face:

**Comment by cnafan** [comment]
def oneLessonID(self,value:str):
        print("oneLessonID的值改变，从 {} 变到 {}".format(self.__oneLessonID,value))
        self.__oneLessonID = value

**Comment by cunzao** [comment]
这样子嘛=-=，我以为使这系列事件的唯一标识。不过我还ios上直接订阅会出现你说的这个问题，在windows 自带的日历没有出现这个问题，那我更改uid为课程ID+周数吧。你觉得怎么样？

**Comment by cunzao** [comment]
刚刚看了下你的Pull Request挺好的

**Comment by cnafan** [comment]
诶 为啥有的回复只有邮箱里有 :scream: ，没开同步没收到

**Comment by cunzao** [comment]
因为我删了🙊艾玛，太丢人了🤣，我想了下我为什么可以同一个uid也能导入，因为我是直接在Windows的日历导入的，不过Windows日历不能新建日历，当时我自己试的时候就直接导入，一个一个的删了一晚上，所以我就让去网站导入了🙊
