### ISSUE TITLE
KeyError: 'location'

### ISSUE THREAD

**Issue by daiweiwho** [cunzao/xidian-class-shedule#6]
不知道为什么，出现如下问题
`czHeaders对象创建成功！
初始化成功！czUserClassName: test
idsLoginPostRequst的状态码：200
本次更新后的cookies：<RequestsCookieJar[<Cookie org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE=zh_CN for />, <Cookie JSESSIONID=8tj5zCeZJVuacC4PwgFAJSV3EbNKIGya_G8uu6cn-1ce5SJoNUXo!904979760 for ids.xidian.edu.cn/>, <Cookie route=d30ae89dd032f678d058485f52d75346 for ids.xidian.edu.cn/authserver>]>
本次更新后的cookies：<RequestsCookieJar[<Cookie org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE=zh_CN for />, <Cookie JSESSIONID=8tj5zCeZJVuacC4PwgFAJSV3EbNKIGya_G8uu6cn-1ce5SJoNUXo!904979760 for ids.xidian.edu.cn/>, <Cookie route=d30ae89dd032f678d058485f52d75346 for ids.xidian.edu.cn/authserver>]>
Traceback (most recent call last):
  File "D:\kcb\xidian-class-shedule\index.py", line 7, in <module>
    user.login()
  File "D:\kcb\xidian-class-shedule\CZUser.py", line 141, in login
    self.__getTrueCookies()
  File "D:\kcb\xidian-class-shedule\CZUser.py", line 113, in __getTrueCookies
    secondRedirectURL = firstRedirectRequst.headers['Location']
  File "D:\python\lib\site-packages\requests\structures.py", line 54, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'location'`

**Comment by cunzao** [comment]
BUG修复了，欢迎测试哦。谢谢你的ISSUE
